### ISSUE TITLE
Not a Issue, but a link to the display board has not been included

### ISSUE THREAD

**Issue by MAVA916** [ThomasHeb/2AxisLaserCutter#1]
Good day Thomas,

Thank you for sharing your 2-AxisLaserCutter with the whole world! I'm very interested in building it for making R/C model gliders too. I found your link to your 4-AxisFoamCutter on RCgroups in the CNC section.

Again not an issue but in the Bill Of Materials their is no direct link to the display board, and tried to search the display board under bigtree-tech.com, and found nothing like in your pictures(with the red circuit board), so it must be a clone from another vendor, or a replacement part for another kind of machine.

Can you update your Github build to include the direct link to the display board?

Thank you for your work on this laser cutter.

Martin

**Comment by ThomasHeb** [comment]
Hello Martin,

you are right, I linked to a wrong bundle.
I bought Arduino, Ramps, Display and Stepper Driver in one bundle, but linked one without display.

Display:
https://www.amazon.de/Redrex-Vollgrafik-Display-Controller-3D-Drucker-Arduino/dp/B01LO20XGS/ref=psdc_6589298031_t3_B07DJ3WBCP

Bundle
https://de.banggood.com/Geekcreit-LCD-12864-RAMPS-1_4-Board-2560-R3-Control-Board-A4988-Driver-Kit-For-3D-Printer-p-936768.html?cur_warehouse=CN&rmmds=search)
or
https://www.amazon.de/Controller-Schrittmotor-Treiber-Heatsink-Grafik-Smart-Display-Controller-3D-Drucker/dp/B01NCZ09Q5/ref=sr_1_15?__mk_de_DE=ÅMÅŽÕÑ&dchild=1&keywords=ramps+1.4+display+arduino&qid=1619111198&s=industrial&sr=1-15
or in Germany:
https://www.roboter-bausatz.de/p/ramps-1.4-kit-12864-lcd-controller
or
https://www.roboter-bausatz.de/p/ramps-1.4-kit-12864-lcd-controller-drv8825-schrittmotoren
other Steppers, but should work, too

Best regards
Thomas
