### ISSUE TITLE
XPS with laser?

### ISSUE THREAD

**Issue by neo2001cro** [ThomasHeb/2AxisLaserCutter#2]
ThomasHeb Hi
A see that you have dialed in your 2AxisLaserCutter to cut wood (balsa?) super, you 'cut' in one go the table to ;)
Have you maybe try to cut 3-5mm XPS, Foam with laser?

**Comment by ThomasHeb** [comment]
Hello Neo,

I used to cut balsa with medium power: 3mm balsa with 40% power and 500mm/min (S40F500) and 5 repeats to cut through.
For Foam (XPS) I go with 10% power and 750mm/min (S10F750) and 5 repeats for 5mm


Regards
Thomas

**Comment by neo2001cro** [comment]
Hi ThomasHeb

1x optional red and black connector on the billing list is 'dead'.?

And if my 'math' is corect, today on 6.8.2021 your LaserCutter cost about ~315 €

![Biling list Aliexpress 208€](https://user-images.githubusercontent.com/88445827/128514891-c929d726-8625-48f7-8a0d-5d119fb9e6d5.jpg)
![Biling list Banggood 107€](https://user-images.githubusercontent.com/88445827/128515210-fddf49aa-c674-46ac-bab9-5fdff9a3cec8.jpg)

**Comment by ThomasHeb** [comment]
The connectors are just for the input voltage.... search for something like this (google: connector 4mm lab)
![Bildschirmfoto 2021-08-06 um 18 16 43](https://user-images.githubusercontent.com/16707487/128541144-45379eda-219b-4ce9-8dd2-f55e2ae108f4.png)

Price looks good! But be aware, that the laser cutter was a project for me (firmware, SketchUp, ...). You can buy a ready to run version for less than 300 EUR

https://de.banggood.com/search/laser-cutter.html?from=nav

**Comment by neo2001cro** [comment]
Hi, ThomasHeb

Thank you for clearing 'missing' parts

:) i know that to (that there is 'redy to run' solutions), and my question is, is your Laser Cutter better then 'ready to run'?

I see that you are very smart man, so, there must be 'reason' that you have go on that 'project'. If i may ask, why ;) ?
I will try to guess, you just wanna to 'refresh' your knowledge ;) :P

**Comment by ThomasHeb** [comment]
I had three reasons to go for an own build:
- I had most of the parts already here
- I wanted to do it as my own project ;P
- I wanted a solution without PC (SD Card + Display), my workbench is always dusted.

My solution is optimized for cutting only (firmware in Arduino). If you want do do engraving, especially with different shading, I would recommend to go for a ‚ready to run‘. In addition the size of the gcode will get very big for engraving (dot by dot) and therefor a PC is needed to send the gcode.

**Comment by neo2001cro** [comment]
ThomasHeb Hi

i have alredy ask so many stupid ;) questions, so here goes two more ;)
Have you look on 'ready to run' solutions, do you have yours 'favorite'?
And, yours solution of working with, and from Sketchup is 'feature' that i like a lot! Respect.
So, can i use your software solution on 'ready to run'?

**Comment by ThomasHeb** [comment]
Hi Neo,

I didn‘t look for ready to run solutions.

SketchUp Plugin is generating gcode, including power settings and travel speed, it is a simple text file. you can send this file via usb to any laser engraver with a universal gcode sender.

**Comment by ThomasHeb** [comment]
closed due to no traffic
